[package]
name = "tempo-eyre"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
indenter = "0.3.0"

[lints]
workspace = true
