version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "A-dependencies"
      - "A-ci"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 1
    groups:
      actions-weekly:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "A-dependencies"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 1
    groups:
      cargo-weekly:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]