[package]
name = "tempo-telemetry-util"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
jiff.workspace = true
tracing.workspace = true
