[workspace]
resolver = "3"
members = ["app", "library"]

[workspace.dependencies]
anyhow = "1.0.98"
tokio = { version = "1.45.1", features = ["full"] }
serde_json = "1.0.140"
eyre = "0.6.12"
serde = {version = "1.0.219", features = ["derive"]}
rand = "0.9.1"

# Reth dependencies
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-node-builder", features = ["test-utils"] }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-tasks" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-chainspec" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-ethereum-primitives" }
reth-consensus= { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-consensus" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-ethereum" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-primitives" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-execution-types" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-primitives-traits" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-node-core" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-node-ethereum" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-provider" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-rpc-builder" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-rpc-eth-api" }

# Alloy dependencies
alloy = { version = "1.0.9", default-features = false }

# Malachite dependencies
malachite-core-types = { git = "https://github.com/informalsystems/malachite", branch = "main", package = "informalsystems-malachitebft-core-types" }
malachitebft-app-channel = { git = "https://github.com/informalsystems/malachite", branch = "main", package = "informalsystems-malachitebft-app-channel" }
malachitebft-proto = { git = "https://github.com/informalsystems/malachite", branch = "main", package = "informalsystems-malachitebft-proto" }
