[workspace]
resolver = "3"
members = ["app", "library"]

[workspace.dependencies]
anyhow = "1.0.98"
tokio = { version = "1.45.1", features = ["full"] }
serde_json = "1.0.140"
eyre = "0.6.12"
serde = {version = "1.0.219", features = ["derive"]}
rand = "0.9.1"
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
hex = "0.4"
redb = "2.6.0"
thiserror = "2.0.12" 

# Reth dependencies
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-node-builder", features = ["test-utils"] }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-tasks" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-chainspec" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-ethereum-primitives" }
reth-consensus= { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-consensus" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-ethereum" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-primitives" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-ethereum-engine-primitives" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-payload-primitives" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-execution-types" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-primitives-traits" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-node-core" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-node-ethereum" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-provider" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-rpc-builder" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-rpc-eth-api" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-trie-db" }
reth-storage-api = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-storage-api" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-cli" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-cli-commands" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-tracing" }
reth-db = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-db" }
reth-ethereum-forks = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-ethereum-forks" }
reth = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", branch = "main", package = "reth-cli-util" }

# Alloy dependencies
alloy = { version = "1.0.9", default-features = false }
alloy-genesis = "1.0.9"
alloy-primitives = "1.0.9"
alloy-eips = "1.0.9"
alloy-consensus = "1.0.9"

# Malachite dependencies
malachitebft-core-types = { git = "https://github.com/informalsystems/malachite", branch = "no-dns", package = "informalsystems-malachitebft-core-types" }
malachitebft-app-channel = { git = "https://github.com/informalsystems/malachite", branch = "no-dns", package = "informalsystems-malachitebft-app-channel" }

[patch.crates-io]
libp2p-dns = { git = "https://github.com/informalsystems/rust-libp2p.git", branch = "reth" }
