[workspace.package]
version = "1.0.2"
edition = "2024"
rust-version = "1.91.0"
license = "MIT OR Apache-2.0"
publish = false

[workspace]
members = [
  "bin/tempo",
  "bin/tempo-bench",
  "bin/tempo-sidecar",
  "crates/alloy",
  "crates/chainspec",
  "crates/commonware-node",
  "crates/commonware-node-config",
  "crates/dkg-onchain-artifacts",
  "crates/consensus",
  "crates/eyre",
  "crates/evm",
  "crates/e2e",
  "crates/faucet",
  "crates/node",
  "crates/payload/builder",
  "crates/payload/types",
  "crates/precompiles",
  "crates/precompiles-macros",
  "crates/primitives",
  "crates/contracts",
  "crates/telemetry-util",
  "crates/transaction-pool",
  "crates/revm",
  "xtask",
]

# Resolver 3 is available with edition 2024
resolver = "3"

[workspace.lints]
[workspace.lints.clippy]
dbg-macro = "warn"
manual-string-new = "warn"
uninlined-format-args = "warn"
use-self = "warn"
redundant-clone = "warn"
default-constructed-unit-structs = "allow"

[workspace.lints.rust]
rust-2018-idioms = "warn"
unreachable-pub = "warn"
unused-must-use = "warn"
redundant-lifetimes = "warn"
unnameable-types = "warn"

[workspace.lints.rustdoc]
all = "warn"

# Speed up compilation time for dev builds by reducing emitted debug info.
# NOTE: Debuggers may provide less useful information with this setting.
# Uncomment this section if you're using a debugger.
[profile.dev]
# https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
debug = "line-tables-only"
split-debuginfo = "unpacked"

# Meant for testing - all optimizations, but with debug assertions and overflow checks.
[profile.hivetests]
inherits = "test"
opt-level = 3
lto = "thin"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

# Use the `--profile profiling` flag to show symbols in release mode.
# e.g. `cargo build --profile profiling`
[profile.profiling]
inherits = "release"
debug = "line-tables-only"
strip = "none"
incremental = true

# Include debug info in benchmarks too.
[profile.bench]
inherits = "profiling"

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

[workspace.dependencies]
tempo-alloy = { path = "crates/alloy" }
tempo-node = { path = "crates/node" }
tempo-chainspec = { path = "crates/chainspec", default-features = false }
tempo-commonware-node = { path = "crates/commonware-node", default-features = false }
tempo-commonware-node-config = { path = "crates/commonware-node-config", default-features = false }
tempo-consensus = { path = "crates/consensus", default-features = false }
tempo-dkg-onchain-artifacts = { path = "crates/dkg-onchain-artifacts", default-features = false }
tempo-e2e = { path = "crates/e2e" }
tempo-faucet = { path = "crates/faucet", default-features = false }
tempo-evm = { path = "crates/evm", default-features = false }
tempo-eyre = { path = "crates/eyre", default-features = false }
tempo-revm = { path = "crates/revm", default-features = false }
tempo-payload-builder = { path = "crates/payload/builder", default-features = false }
tempo-payload-types = { path = "crates/payload/types", default-features = false }
tempo-precompiles = { path = "crates/precompiles", default-features = false }
tempo-precompiles-macros = { path = "crates/precompiles-macros" }
tempo-primitives = { path = "crates/primitives", default-features = false, features = [
  "reth",
] }
tempo-contracts = { path = "crates/contracts", default-features = false }
tempo-telemetry-util = { path = "crates/telemetry-util", default-features = false }
tempo-transaction-pool = { path = "crates/transaction-pool", default-features = false }

# reth v1.10.1
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-cli-runner = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-consensus-common = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-e2e-test-utils = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-engine-tree = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-errors = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-eth-wire-types = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-ethereum-cli = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-ethereum-consensus = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b", default-features = false }
reth-evm = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-metrics = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-node-metrics = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b", default-features = false }
reth-provider = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-rpc-convert = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-storage-api = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b" }

reth-revm = { git = "https://github.com/paradigmxyz/reth", rev = "bb1df5b", features = [
  "std",
  "optional-checks",
] }
revm = { version = "34.0.0", features = ["optional_fee_charge"] }

alloy = { version = "1.4.3", default-features = false }
alloy-consensus = { version = "1.4.3", default-features = false }
alloy-contract = { version = "1.4.3", default-features = false }
alloy-eips = { version = "1.4.3", default-features = false }
alloy-evm = "0.26.3"
revm-inspectors = "0.34.0"
alloy-genesis = "1.4.3"
alloy-hardforks = "0.4.5"
alloy-network = { version = "1.4.3", default-features = false }
alloy-primitives = { version = "1.5.0", default-features = false }
alloy-provider = { version = "1.4.3", default-features = false }
alloy-rlp = "0.3.12"
alloy-rpc-types-engine = "1.4.3"
alloy-rpc-types-eth = { version = "1.4.3" }
alloy-serde = "1.4.3"
alloy-signer = "1.4.3"
alloy-signer-local = "1.4.3"
alloy-sol-types = "1.5.0"
alloy-transport = "1.4.3"

commonware-broadcast = "0.0.65"
commonware-codec = "0.0.65"
commonware-consensus = "0.0.65"
commonware-cryptography = "0.0.65"
commonware-macros = "0.0.65"
commonware-math = "0.0.65"
commonware-p2p = "0.0.65"
commonware-parallel = "0.0.65"
commonware-runtime = "0.0.65"
commonware-storage = "0.0.65"
commonware-utils = "0.0.65"

arbitrary = { version = "1.3", features = ["derive"] }
async-lock = "3.4.1"
async-trait = "0.1"
auto_impl = "1"
axum = "0.8.4"
base64 = "0.22"
bytes = "1.8"
clap = { version = "4.5.45", features = ["derive"] }
const-hex = { version = "1.15.0" }
derive_more = { version = "2.0.0" }
eyre = "0.6.12"
futures = "0.3.31"
governor = "0.10.2"
indexmap = "2.11.0"
indicatif = "0.18"
itertools = "0.14.0"
jiff = { version = "0.2.15", default-features = false }
jsonrpsee = { version = "0.26.0", features = ["server", "client", "macros"] }
metrics = "0.24.0"
p256 = "0.13"
parking_lot = "0.12.4"
prometheus-client = "0.24.0"
proptest = "1.7"
proptest-arbitrary-interop = "0.1.0"
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
schnellru = "0.2"
sha2 = "0.10"
tempfile = "3.20.0"
thiserror = "2.0.14"
# TODO: restrict this to only the required features
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.16"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
criterion = "0.7.0"
test-case = "3"
secp256k1 = "0.30.0"
pyroscope = "0.5.8"
pyroscope_pprofrs = "0.2.10"
rayon = "1.10"

# build deps
vergen = "9.1.0"
vergen-git2 = "9.1.0"

# [patch."https://github.com/paradigmxyz/reth"]
# reth-basic-payload-builder = { path = "../reth/crates/payload/basic" }
# reth-chain-state = { path = "../reth/crates/chain-state" }
# reth-chainspec = { path = "../reth/crates/chainspec" }
# reth-cli = { path = "../reth/crates/cli/cli" }
# reth-cli-commands = { path = "../reth/crates/cli/commands" }
# reth-cli-runner = { path = "../reth/crates/cli/runner" }
# reth-cli-util = { path = "../reth/crates/cli/util" }
# reth-codecs = { path = "../reth/crates/storage/codecs" }
# reth-codecs-derive = { path = "../reth/crates/storage/codecs/derive" }
# reth-config = { path = "../reth/crates/config" }
# reth-consensus = { path = "../reth/crates/consensus/consensus" }
# reth-consensus-common = { path = "../reth/crates/consensus/common" }
# reth-db = { path = "../reth/crates/storage/db" }
# reth-db-api = { path = "../reth/crates/storage/db-api" }
# reth-e2e-test-utils = { path = "../reth/crates/e2e-test-utils" }
# reth-engine-local = { path = "../reth/crates/engine/local" }
# reth-engine-primitives = { path = "../reth/crates/engine/primitives" }
# reth-engine-tree = { path = "../reth/crates/engine/tree" }
# reth-errors = { path = "../reth/crates/errors" }
# reth-eth-wire-types = { path = "../reth/crates/net/eth-wire-types" }
# reth-ethereum = { path = "../reth/crates/ethereum/reth" }
# reth-ethereum-cli = { path = "../reth/crates/ethereum/cli" }
# reth-ethereum-consensus = { path = "../reth/crates/ethereum/consensus" }
# reth-ethereum-engine-primitives = { path = "../reth/crates/ethereum/engine-primitives" }
# reth-ethereum-forks = { path = "../reth/crates/ethereum/hardforks" }
# reth-ethereum-primitives = { path = "../reth/crates/ethereum/primitives" }
# reth-evm = { path = "../reth/crates/evm/evm" }
# reth-evm-ethereum = { path = "../reth/crates/ethereum/evm" }
# reth-execution-errors = { path = "../reth/crates/evm/execution-errors" }
# reth-execution-types = { path = "../reth/crates/evm/execution-types" }
# reth-exex-types = { path = "../reth/crates/exex/types" }
# reth-metrics = { path = "../reth/crates/metrics" }
# reth-net-banlist = { path = "../reth/crates/net/banlist" }
# reth-network = { path = "../reth/crates/net/network" }
# reth-network-p2p = { path = "../reth/crates/net/p2p" }
# reth-network-peers = { path = "../reth/crates/net/peers" }
# reth-network-types = { path = "../reth/crates/net/network-types" }
# reth-node-api = { path = "../reth/crates/node/api" }
# reth-node-builder = { path = "../reth/crates/node/builder" }
# reth-node-core = { path = "../reth/crates/node/core" }
# reth-node-ethereum = { path = "../reth/crates/ethereum/node" }
# reth-node-metrics = { path = "../reth/crates/node/metrics" }
# reth-payload-builder = { path = "../reth/crates/payload/builder" }
# reth-payload-primitives = { path = "../reth/crates/payload/primitives" }
# reth-primitives-traits = { path = "../reth/crates/primitives-traits" }
# reth-provider = { path = "../reth/crates/storage/provider" }
# reth-prune = { path = "../reth/crates/prune/prune" }
# reth-prune-types = { path = "../reth/crates/prune/types" }
# reth-revm = { path = "../reth/crates/revm" }
# reth-rpc = { path = "../reth/crates/rpc/rpc" }
# reth-rpc-api = { path = "../reth/crates/rpc/rpc-api" }
# reth-rpc-builder = { path = "../reth/crates/rpc/rpc-builder" }
# reth-rpc-convert = { path = "../reth/crates/rpc/rpc-convert" }
# reth-rpc-eth-api = { path = "../reth/crates/rpc/rpc-eth-api" }
# reth-rpc-eth-types = { path = "../reth/crates/rpc/rpc-eth-types" }
# reth-rpc-server-types = { path = "../reth/crates/rpc/rpc-server-types" }
# reth-stages-api = { path = "../reth/crates/stages/api" }
# reth-stages-types = { path = "../reth/crates/stages/types" }
# reth-static-file = { path = "../reth/crates/static-file/static-file" }
# reth-static-file-types = { path = "../reth/crates/static-file/types" }
# reth-storage-api = { path = "../reth/crates/storage/storage-api" }
# reth-storage-errors = { path = "../reth/crates/storage/errors" }
# reth-tasks = { path = "../reth/crates/tasks" }
# reth-tokio-util = { path = "../reth/crates/tokio-util" }
# reth-tracing = { path = "../reth/crates/tracing" }
# reth-transaction-pool = { path = "../reth/crates/transaction-pool" }
# reth-trie = { path = "../reth/crates/trie/trie" }
# reth-trie-common = { path = "../reth/crates/trie/common" }
# reth-trie-db = { path = "../reth/crates/trie/db" }
# reth-trie-parallel = { path = "../reth/crates/trie/parallel" }
# reth-trie-sparse = { path = "../reth/crates/trie/sparse" }
# reth-trie-sparse-parallel = { path = "../reth/crates/trie/sparse-parallel" }

[patch.crates-io]
# Commonware right after after PR #2841 was merged
commonware-broadcast = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-codec = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-consensus = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-cryptography = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-macros = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-math = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-p2p = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-parallel = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-runtime = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-storage = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
commonware-utils = { git = "https://github.com/commonwarexyz/monorepo", rev = "374285d20a3333acf06ffd954e6eb7eb2826568e"}
