# msrv = "1.86"
# # These are some of clippy's nursery (i.e., experimental) lints that we like.
# # By default, nursery lints are allowed. Some of the lints below have made good
# # suggestions which we fixed. The others didn't have any findings, so we can
# # assume they don't have that many false positives. Let's enable them to
# # prevent future problems.
# borrow-as-ptr = "warn"
# branches-sharing-code = "warn"
# clear-with-drain = "warn"
# cloned-instead-of-copied = "warn"
# collection-is-never-read = "warn"
# dbg-macro = "warn"
# derive-partial-eq-without-eq = "warn"
# doc-markdown = "warn"
# empty-line-after-doc-comments = "warn"
# empty-line-after-outer-attr = "warn"
# enum-glob-use = "warn"
# equatable-if-let = "warn"
# explicit-into-iter-loop = "warn"
# explicit-iter-loop = "warn"
# flat-map-option = "warn"
# from-iter-instead-of-collect = "warn"
# if-not-else = "warn"
# if-then-some-else-none = "warn"
# implicit-clone = "warn"
# imprecise-flops = "warn"
# iter-on-empty-collections = "warn"
# iter-on-single-items = "warn"
# iter-with-drain = "warn"
# iter-without-into-iter = "warn"
# large-stack-frames = "warn"
# manual-assert = "warn"
# manual-clamp = "warn"
# manual-is-variant-and = "warn"
# manual-string-new = "warn"
# match-same-arms = "warn"
# missing-const-for-fn = "warn"
# mutex-integer = "warn"
# naive-bytecount = "warn"
# needless-bitwise-bool = "warn"
# needless-continue = "warn"
# needless-for-each = "warn"
# needless-pass-by-ref-mut = "warn"
# nonstandard-macro-braces = "warn"
# option-as-ref-cloned = "warn"
# or-fun-call = "warn"
# path-buf-push-overwrite = "warn"
# read-zero-byte-vec = "warn"
# result-large-err = "allow"
# redundant-clone = "warn"
# redundant-else = "warn"
# single-char-pattern = "warn"
# string-lit-as-bytes = "warn"
# string-lit-chars-any = "warn"
# suboptimal-flops = "warn"
# suspicious-operation-groupings = "warn"
# trailing-empty-array = "warn"
# trait-duplication-in-bounds = "warn"
# transmute-undefined-repr = "warn"
# trivial-regex = "warn"
# tuple-array-conversions = "warn"
# type-repetition-in-bounds = "warn"
# uninhabited-references = "warn"
# unnecessary-self-imports = "warn"
# unnecessary-struct-initialization = "warn"
# unnested-or-patterns = "warn"
# unused-peekable = "warn"
# unused-rounding = "warn"
# use-self = "warn"
# useless-let-if-seq = "warn"
# while-float = "warn"
# zero-sized-map-values = "warn"
# allow-attributes = "warn"
# allow-attributes-without-reason = "warn"
#
# # These are nursery lints which have findings. Allow them for now. Some are not
# # quite mature enough for use in our codebase and some we don't really want.
# # Explicitly listing should make it easier to fix in the future.
# as-ptr-cast-mut = "allow"
# cognitive-complexity = "allow"
# debug-assert-with-mut-call = "allow"
# fallible-impl-from = "allow"
# future-not-send = "allow"
# needless-collect = "allow"
# non-send-fields-in-send-ty = "allow"
# redundant-pub-crate = "allow"
# significant-drop-in-scrutinee = "allow"
# significant-drop-tightening = "allow"
# too-long-first-doc-paragraph = "allow"
