[files]
extend-exclude = [
    ".git",
    "target",
    "testdata",
    "Cargo.toml",
    "Cargo.lock",
    "*.json",
    "**/ph.js",
    "**/tests/**",
    "**/test/**",
    "**/*_test.*",
    "**/*_tests.*",
    "docs/specs/lib/**",
]

[default.extend-words]
ba = "ba"
multline = "multline"
froms = "froms"
Nam = "Nam"
prool = "prool"
Prool = "Prool"
