[package]
name = "tempo-bench"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
# Tempo
tempo-alloy.workspace = true
tempo-precompiles = { workspace = true, features = ["rpc"] }
tempo-contracts.workspace = true

# Workspace dependencies
alloy = { workspace = true, features = [
    "genesis",
    "getrandom",
    "network",
    "rand",
    "reqwest",
    "signer-local",
    "signer-mnemonic",
    "signers",
    "sol-types",
    "contract",
] }
alloy-consensus = { workspace = true, features = ["secp256k1"] }
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
futures.workspace = true
itertools.workspace = true
reth-tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
tokio.workspace = true

# Bespoke dependencies
indicatif = { workspace = true, features = ["rayon", "futures"] }
mimalloc = "0.1.47"
rayon.workspace = true
rlimit = "0.10.2"
governor = "0.10.1"
rand = "0.9.2"
rand_08 = { package = "rand", version = "0.8" }
clickhouse = { version = "0.13", features = ["uuid", "time", "rustls-tls"] }
uuid = { version = "1", features = ["v4", "serde"] }
time = "0.3"
