[package]
name = "tempo-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TODO:"

[lints]
workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "sol-types", "rpc"] }

