[package]
name = "tempo-xtask"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-commonware-node-config.workspace = true
tempo-commonware-node-cryptography.workspace = true

alloy-primitives.workspace = true
camino = "1.1.11"
clap = { version = "4.5.45", features = ["derive"] }
commonware-cryptography.workspace = true
commonware-utils.workspace = true
eyre.workspace = true
indexmap.workspace = true
rand.workspace = true
toml.workspace = true
