[package]
name = "tempo-sidecar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
alloy = { workspace = true, default-features = false, features = ["network", "rpc", "rpc-types", "transports", "providers", "reqwest-rustls-tls", "signers", "signer-local"] }
eyre.workspace = true
foundry-wallets = { git = "https://github.com/foundry-rs/foundry", rev = "a8dc5ae" }
itertools = "0.14.0"
tempo-precompiles.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots"] }
metrics-exporter-prometheus = { version = "0.17.2", default-features = false }
metrics = "0.24.2"
poem = "3.1.12"
rand_distr = "0.5.1"
tracing-subscriber = {workspace = true, features = ["env-filter"]}
tokio.workspace = true
tracing.workspace = true
