[package]
name = "tempo-sidecar"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
alloy = { workspace = true, default-features = false, features = [
    "network",
    "rpc",
    "rpc-types",
    "transports",
    "providers",
    "provider-ws",
    "reqwest-rustls-tls",
    "signers",
    "signer-local",
    "signer-mnemonic",
    "rand",
] }
tempo-alloy.workspace = true
eyre.workspace = true
futures.workspace = true
hex = "0.4"
itertools = "0.14.0"
tempo-precompiles = { workspace = true, features = ["rpc"] }
reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "rustls",
] }
rustls.workspace = true
metrics-exporter-prometheus = { version = "0.18.1", default-features = false }
metrics = "0.24.3"
poem = "3.1.12"
rand_distr = "0.5.1"
tempo-telemetry-util.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio.workspace = true
tracing.workspace = true
