[package]
name = "tempo-monitor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
alloy = { workspace = true, default-features = false, features = ["network", "rpc", "rpc-types", "transports", "providers", "reqwest-rustls-tls"] }
eyre.workspace = true
itertools = "0.14.0"
tempo-precompiles.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots"] }
metrics-exporter-prometheus = "0.17.2"
metrics = "0.24.2"
poem = "3.1.12"
tracing-subscriber = {workspace = true, features = ["env-filter"]}
tracing-log = "0.2.0"
tokio.workspace = true
log = "0.4.28"
tracing.workspace = true


[lints]
workspace = true
