[package]
name = "tempo-chainspec"
description = "TODO:"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-primitives = { workspace = true, features = ["default"] }

reth-cli.workspace = true
reth-chainspec.workspace = true
reth-network-peers.workspace = true
reth-ethereum = { workspace = true, features = ["evm"] }

alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-hardforks.workspace = true

eyre.workspace = true
serde.workspace = true
serde_json.workspace = true

[features]
default = ["serde"]
serde = [
    "alloy-eips/serde",
    "alloy-hardforks/serde",
    "alloy-primitives/serde",
    "tempo-primitives/serde"
]
