[package]
name = "tempo-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TODO:"

# [lints]
# workspace = true

[dependencies]
tempo-evm.workspace = true
reth-cli.workspace = true
reth-chainspec.workspace = true
reth-cli-runner.workspace = true
reth-cli-commands.workspace = true
reth-node-metrics.workspace = true
reth-network-peers.workspace = true
reth-ethereum-cli.workspace = true
reth-ethereum = { workspace = true, features = ["cli", "full"] }
reth-tracing.workspace = true
eyre.workspace = true
serde_json.workspace = true
alloy-genesis.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-eips.workspace = true
clap.workspace = true
tracing.workspace = true
