[network_worker]
target_urls = ["http://127.0.0.1:8545"]
total_connections = 10_000 # Limited by # of ephemeral ports.

batch_factor = 1

max_concurrent_setup_requests = 100
error_sleep_ms = 100
tx_queue_empty_sleep_ms = 25

[tx_gen_worker]
chain_id = 31337

mnemonic = "test test test test test test test test test test test junk"
num_accounts = 1000 # Limited by the number in the genesis (see generate_genesis_alloc.rs)

gas_price = 100000000000 # 100 gwei
gas_limit = 100_000

token_contract_address = "0x2000000000000000000000000000000000000001"
recipient_distribution_factor = 1 # 1/20 of accounts receive transfers.
max_transfer_amount = 10

batch_size = 1_000 # Number of transactions to generate before pushing to queue.

[rate_limiting]
initial_ratelimit = 100 # txs/s

# Rate limit thresholds: [(threshold, rate_limit)]
# threshold = number of transactions sent
# rate_limit = new transactions per second limit
ratelimit_thresholds = [
    [1_562, 1000],      # NUM_ACCOUNTS / 16
]

[workers]
thread_pinning = false
tx_gen_worker_percentage = 0.1
network_worker_percentage = 0.9

[reporters]
tx_queue_report_interval_secs = 3
network_stats_report_interval_secs = 3
