[package]
name = "tempo-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
reth-revm.workspace = true
alloy-primitives.workspace = true
tempo-precompiles.workspace = true

eyre.workspace = true
tracing.workspace = true
