[package]
name = "tempo-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
reth-evm.workspace = true
alloy-primitives.workspace = true
tempo-precompiles.workspace = true

tracing.workspace = true

[dev-dependencies]
eyre.workspace = true
