[package]
name = "tempo-revm"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-precompiles.workspace = true
tempo-primitives.workspace = true
tempo-contracts.workspace = true

reth-evm.workspace = true

revm.workspace = true

alloy-evm.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-sol-types.workspace = true

derive_more.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
eyre.workspace = true
alloy-primitives = { workspace = true, features = ["rand"] }
