[package]
name = "tempo-revm"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-precompiles.workspace = true
tempo-primitives.workspace = true
tempo-contracts.workspace = true

reth-evm.workspace = true
reth-rpc-convert = { workspace = true, optional = true }

alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-eth = { workspace = true, optional = true }

derive_more.workspace = true
tracing.workspace = true

[dev-dependencies]
eyre.workspace = true
alloy-primitives = { workspace = true, features = ["rand"] }

[features]
default = ["rpc"]
rpc = ["dep:alloy-rpc-types-eth", "dep:reth-rpc-convert"]
