[package]
name = "crescendo"
version.workspace = true
edition.workspace = true

[[bin]]
name = "crescendo"
path = "bin/crescendo.rs"

[[bin]]
name = "generate-genesis-alloc"
path = "bin/generate_genesis_alloc.rs"

[dependencies]
alloy = { workspace = true, features = ["genesis", "signers", "signer-local", "network", "sol-types"] }
alloy-consensus = { workspace = true, features = ["secp256k1"] }
alloy-evm = "0.13"
alloy-signer-local = { version = "1", features = ["mnemonic"] }
clap = { workspace = true, features = ["derive", "env"] }
core_affinity = "0.8.3"
crossbeam-utils = "0.8.21"
dashmap = "6.1"
eyre.workspace = true
hex.workspace = true
http = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
mimalloc = "0.1.47"
num_cpus = "1.17.0"
parking_lot = "0.12.4"
rand.workspace = true
ratelimit = "0.10"
rayon = "1.10"
rlimit = "0.10.2"
serde.workspace = true
serde_json.workspace = true
simple-tqdm = { version = "0.2.0", features = ["rayon"] }
thousands = "0.2.0"
tokio.workspace = true
tokio-metrics = "0.4.3"
toml.workspace = true
