[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]

eyre.workspace = true
serde.workspace = true
rand.workspace = true
clap.workspace = true
tracing.workspace = true
hex.workspace = true
tokio.workspace = true
redb.workspace = true
thiserror.workspace = true

# Malachite dependencies
malachitebft-core-types.workspace = true
malachitebft-app-channel.workspace = true

# Reth dependencies
reth-chainspec.workspace = true
reth-tasks.workspace = true
reth-ethereum-primitives.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-consensus.workspace = true
reth-primitives.workspace = true
reth-execution-types.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-rpc-builder.workspace = true
reth-rpc-eth-api.workspace = true
reth-trie-db.workspace = true
reth-storage-api.workspace = true
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-tracing.workspace = true
reth-db.workspace = true
reth-ethereum-forks.workspace = true
reth.workspace = true
reth-payload-primitives.workspace = true
reth-ethereum-engine-primitives.workspace = true

alloy-eips.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
