[package]
name = "tempo-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# [lints]
# workspace = true

[dependencies]
alloy.workspace = true
reth-rpc.workspace = true
reth-rpc-convert.workspace = true
reth-node-api.workspace = true
reth-storage-api.workspace = true
reth-tasks.workspace = true
reth-rpc-eth-api.workspace = true
reth-rpc-eth-types.workspace = true
