[package]
name = "tempo-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# [lints]
# workspace = true

[dependencies]
reth-rpc.workspace = true
reth-rpc-convert.workspace = true
