#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Tempo Team
  description: Bootstrap role for basic system setup and security
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - system
    - security
    - firewall
    - bootstrap