route:
  group_by: ['alertname']
  repeat_interval: 3h
  receiver: 'tempoxyz-incidentio'
receivers:
- name: 'tempoxyz-incidentio'
  webhook_configs:
    - url: 'https://api.incident.io/v2/alert_events/alertmanager/01K2YE7CM0MTMK2N4RN8D3M5A0'
      send_resolved: true
      http_config:
        authorization:
          credentials: '${INCIDENTIO_API_KEY}'

