[package]
name = "tempo-arber"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "signer-mnemonic", "reqwest-rustls-tls"] }
dashmap = "6.1"
eyre.workspace = true
tokio = { workspace = true, features = ["macros"] }
tempo-precompiles = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
itertools = "0.14.0"
tracing.workspace = true
foundry-wallets = { git = "https://github.com/foundry-rs/foundry", rev = "a8dc5ae" }
tracing-subscriber = "0.3"

[lints]
workspace = true
