[package]
name = "tempo-arber"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "signer-mnemonic", "reqwest-rustls-tls"] }
eyre.workspace = true
tokio = { workspace = true, features = ["macros"] }
tempo-precompiles = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
tracing.workspace = true
foundry-evm = { git = "https://github.com/foundry-rs/foundry", tag = "v1.3.6" }
foundry-wallets = { git = "https://github.com/foundry-rs/foundry", tag = "v1.3.6" }
tracing-subscriber = "0.3"

[lints]
workspace = true
