[package]
name = "tempo-alloy"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-primitives.workspace = true
tempo-evm.workspace = true # todo: make this optional
tempo-revm.workspace = true # todo: make this optional

alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-eth.workspace = true

# todo: make these optional
reth-evm.workspace = true
reth-rpc-convert.workspace = true

serde.workspace = true

[dev-dependencies]
test-case.workspace = true

[features]
default = []
asm-keccak = [
    "alloy-primitives/asm-keccak",
]
