[package]
name = "tempo-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TODO:"

# [lints]
# workspace = true

[dependencies]
tempo-precompiles.workspace = true
tempo-revm.workspace = true
reth.workspace = true
reth-evm.workspace = true
reth-revm.workspace = true
alloy-primitives.workspace = true

