[package]
name = "tempo-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TODO:"

[lints]
workspace = true

[dependencies]
tempo-precompiles.workspace = true
tempo-revm.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true

