[package]
name = "tempo-faucet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TODO:"

# [lints]
# workspace = true

[dependencies]
reth.workspace = true
tempo-precompiles.workspace = true
tempo-transaction-pool.workspace = true
alloy = {workspace = true, features = ["signers", "signer-local", "signer-mnemonic-all-languages"]}
async-trait.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
clap.workspace = true

[dev-dependencies]
criterion.workspace = true

[build-dependencies]
prost-build.workspace = true
protox.workspace = true
