[package]
name = "tempo-precompiles"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "TODO:"

[lints]
workspace = true

[dependencies]
tempo-contracts.workspace = true
reth-evm.workspace = true
reth-storage-api.workspace = true
alloy = { workspace = true, default-features = false }
alloy-evm.workspace = true

tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
alloy-signer.workspace = true
alloy-signer-local.workspace = true
alloy-primitives = { workspace = true, features = ["rand"] }
eyre.workspace = true
rand.workspace = true

[[bench]]
name = "tempo_precompiles"
harness = false
