[package]
name = "tempo-precompiles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TODO:"

# [lints]
# workspace = true

[dependencies]
reth-evm.workspace = true
alloy = { workspace = true, features = ["contract", "sol-types", "rpc"] }
alloy-evm.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
eyre.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "08fa016ed950b6e65f810fc9cdef7cf38fbc63f6" }
alloy-signer-local = { git = "https://github.com/alloy-rs/alloy", rev = "08fa016ed950b6e65f810fc9cdef7cf38fbc63f6" }
alloy-primitives = { workspace = true, features = ["rand"] }

[[bench]]
name = "tempo_precompiles"
harness = false
