[package]
name = "tempo-precompiles"
description = "TODO:"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-contracts.workspace = true
reth-storage-api = { workspace = true, optional = true }
alloy = { workspace = true, features = ["contract", "sol-types", "rpc"] }
alloy-evm.workspace = true
revm.workspace = true

tracing.workspace = true
thiserror.workspace = true
derive_more.workspace = true

[dev-dependencies]
criterion.workspace = true
alloy-signer.workspace = true
alloy-signer-local.workspace = true
alloy-primitives = { workspace = true, features = ["rand"] }
eyre.workspace = true
rand.workspace = true

[features]
reth = ["dep:reth-storage-api"]

[[bench]]
name = "tempo_precompiles"
harness = false
