[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# TODO(rusowsky): remove once solc patch is released
solc_version = "0.8.31"

[profile.ci]
optimizer = true
optimizer_runs = 1

[fmt]
line_length = 100
sort_imports = true
contract_new_lines = true
bracket_spacing = true
number_underscore = "thousands"
multline_func_header = "all"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
