[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
extra_output = ["storageLayout"]
invariant = { runs = 10, depth = 200, fail_on_revert = true, show_solidity = true }
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.ci]
optimizer = true
optimizer_runs = 1
invariant = { depth = 100, fail_on_revert = true, show_solidity = true }

[fmt]
line_length = 100
sort_imports = true
contract_new_lines = true
bracket_spacing = true
number_underscore = "thousands"
multline_func_header = "all"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
