name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  merge_group:
  workflow_dispatch:
    inputs:
      nightly:
        description: "Tag nightly"
        type: boolean
        default: false
  workflow_call:
  schedule:
    - cron: "5 9 * * *"
    - cron: "30 20 * * *"

env:
  REGISTRY: ghcr.io/tempoxyz

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: depot-ubuntu-latest-16
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: depot/setup-action@c0b08c3ba30137f89e75961508b587484558ff0f # v1.7.0

      - name: Docker metadata for tempo
        id: meta-tempo
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: ${{ env.REGISTRY }}/tempo
          bake-target: tempo
          tags: |
            type=schedule,pattern=nightly
            type=raw,value=nightly,enable=${{ github.event.inputs.nightly == 'true' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=stable,enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=edge,branch=main
            type=sha,prefix=sha-
            type=ref,event=pr

      - name: Docker metadata for tempo-bench
        id: meta-tempo-bench
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: ${{ env.REGISTRY }}/tempo-bench
          bake-target: tempo-bench
          tags: |
            type=schedule,pattern=nightly
            type=raw,value=nightly,enable=${{ github.event.inputs.nightly == 'true' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=stable,enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=edge,branch=main
            type=sha,prefix=sha-
            type=ref,event=pr

      - name: Docker metadata for tempo-sidecar
        id: meta-tempo-sidecar
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: ${{ env.REGISTRY }}/tempo-sidecar
          bake-target: tempo-sidecar
          tags: |
            type=schedule,pattern=nightly
            type=raw,value=nightly,enable=${{ github.event.inputs.nightly == 'true' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=stable,enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=edge,branch=main
            type=sha,prefix=sha-
            type=ref,event=pr

      - name: Docker metadata for tempo-xtask
        id: meta-tempo-xtask
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: ${{ env.REGISTRY }}/tempo-xtask
          bake-target: tempo-xtask
          tags: |
            type=schedule,pattern=nightly
            type=raw,value=nightly,enable=${{ github.event.inputs.nightly == 'true' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=stable,enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=edge,branch=main
            type=sha,prefix=sha-
            type=ref,event=pr

      - name: Log in to Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: shortsha
        run: echo "shortsha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: depot/bake-action@2ae2529115bba41de62b77b345de48d57eca7564 # v1.12.1
        with:
          files: |
            docker-bake.hcl
            ${{ steps.meta-tempo.outputs.bake-file }}
            ${{ steps.meta-tempo-bench.outputs.bake-file }}
            ${{ steps.meta-tempo-sidecar.outputs.bake-file }}
            ${{ steps.meta-tempo-xtask.outputs.bake-file }}
          targets: default
          project: 0c6tg19qsp
          push: true
        env:
          VERGEN_GIT_SHA: ${{ github.sha }}
          VERGEN_GIT_SHA_SHORT: ${{ steps.shortsha.outputs.shortsha }}
