name: Lint

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: "sccache"

jobs:
  clippy:
    name: clippy
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run clippy
        run: cargo clippy --all-targets --all-features --locked
        env:
          RUSTFLAGS: -D warnings

  fmt:
    name: fmt
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check
  
  crate-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --feature-powerset --depth 1

  docs:
    name: docs
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Check documentation
        run: cargo doc --no-deps --document-private-items --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  typos:
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1

  deny:
    uses: ithacaxyz/ci/.github/workflows/deny.yml@main

  zepter:
    name: zepter
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: zepter
      - name: Eagerly pull dependencies
        run: cargo metadata --format-version=1 --locked > /dev/null
      - run: zepter run check

  lint-success:
    name: lint success
    runs-on: depot-ubuntu-latest
    if: always()
    needs:
      - clippy
      - fmt
      - docs
      - typos
      - deny
      - zepter
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
