name: Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: "sccache"

jobs:
  test:
    name: test
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run --exclude tempo-e2e-tests --no-fail-fast --workspace
  msrv:
    name: MSRV
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.88" # MSRV
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Build with MSRV
        run: cargo build --bin tempo
        env:
          RUSTFLAGS: -D warnings

  consensus-e2e-tests:
    name: Consensus E2E Tests
    runs-on: depot-ubuntu-latest-4
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@nextest
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: 0c6tg19qsp
          context: .
          platforms: linux/amd64
          tags: tempo-node:latest
      - name: Run tests
        run: cargo nextest run --exclude tempo-e2e-tests --no-fail-fast --workspace

  test-success:
    name: test success
    runs-on: depot-ubuntu-latest-4
    if: always()
    needs:
      - test
      - msrv
      - consensus-e2e-tests
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
